### ISSUE TITLE
Distros

### ISSUE THREAD

**Issue by StevenBlack** [tds-fdw/tds_fdw#127]
This might be worth considering.

**Background**:  This is probably anecdotal, but may prove worthwhile.  I develop on OS X, deploy on Ubuntu.  Great combo.  But now I need a FDW to a SQL Server database.

This repo appears to be my only option.  I need to build to get something deployable.  The build fails on OSX with the `sybfront.h` error, similar to Issue #63.  Darn!

I build a lot of suff on OS X but, given that OS X wasn't rightly documented until recently – see commit 5663f14 – I ask myself, *"Do I really want to go there?"*.  Given the nature of the system I'm building and maintaining, my instinct says *"No"*.  There's no way I can justify the dependency risk.

Which is a shame.   

I reckon four-fold more developers would use this repo if distros were pre-built and made available.

If it were simple to use the fruits of this repo, I would use it.   I need a turn-key FDW for OS X and Ubuntu, because I have a development queue that's 500-items long and I can't justify the debug-first-then-use workflow that tds_fdw is imposing because straightforward pre-built distros are not available.

So I hope you'll consider making consumer-ready distros of tds_fdw.

**Comment by juliogonzalez** [comment]
Hi @StevenBlack 

To make it more clear for me, do you mean you would like to have "official" RPMs and DEBs so you could run rpm -i or dpkg -i to install, or even having the RPMs and DEBs at yum/apt repositories instead of building by yourself?

**Comment by StevenBlack** [comment]
@juliogonzalez Yes!  

The build-step is problematic because build is failing on (my) OS X boxes (similar to #63). 

The implicit signals are, OS X isn't tier-1 here, which is nominally fine – I get it – but I'm reluctant to hitch since the dependency risk, certainly the technical risk and upfront trial risk, appear high.

There are other facets to this, too much for this thread.  

Let's just say it may cost me a half-day (which I don't have) just to try this in development.  I think it's probably easy to build/deploy to Ubuntu in production, but I need to get there through OS X first.

**Comment by juliogonzalez** [comment]
First of all, I am not the owner of tds_fwd, but I help Geoff with the continuous building, tests, and I also keep an [unofficial repository to create RPMS](https://github.com/juliogonzalez/tds_fdw-rpm).

So I can certainly help with builds and packaging... as long as I have a system to compile and to test.

And the problem is that I don't have access to Apple boxes where I can run OSX to build tds_fdw and to create the DMG package. And even if I could do it using GNU/Linux, I won't be able to test it :-(

However I am not sure I can understand your situation... You mean that your development servers are MacOSX server, while your production servers are Ubuntu? Or do you mean that you use a MacOS box to develop, while production is using Ubuntu?

If it is last case, can you consider a virtual machine or using docker at your local MacOS system? You can even use our [docker images](https://hub.docker.com/u/tdsfdw/dashboard/), since are the same we use to compile.

But if it is the first case, I can't understand why but I am sure you have a strong reason to do it.

For this case, and to provide real MacOSX support, I think that @GeoffMontee would need to be involved since he's the developer and owner and need to see decide what the would be.

And if he wants then we can talk to see what we can do from a technical and economical perspective, (since we would need a virtual or physical MacOS box).

**Comment by StevenBlack** [comment]
MacOS box to develop, while production is using Ubuntu.

----

Here's the thing about Mac that may be interesting:

Like many Mac-based devs I'm waiting (hoping) Apple gets their shit together because the last crop of laptops are gimicky fuckups, compromises that aren't sitting well with most developers.  No hardware escape key, can you imagine??  It's idiotic.  Other models with conventional keyboards aren't available in dev-compatible configurations.

So my Macs are 3+ year old boxes, with several OS updates over the years, along with intervening layers and updates of compilers various package managers.

So I'm pretty far from developing on a vanilla, conventional Mac.  So build errors here could be due to many factors.  I dread having to chase this down merely to try this FDW.

THAT is why a pre-built package would be so welcome here.

**Comment by juliogonzalez** [comment]
Depending on what you need exactly maybe Docker (for containers) or VMs (Vagrant would be ideal) could be an option.

At my current job I have a lot of developers that use MacOSX or even Windows to develop.

Since our production environment is CentOS only, they use their local OS to develop, but a VM at their laptops to build and test.

For this a Vagrant box is ideal (docker could be another option), since they can have a production-like box with CentOS and the same dependencies and packages used at production. And they can destroy and provision VMs really fast if they break something, so that prevent a lot of mistakes and problems at the releases.

Maybe not suitable for your needs as I don't have the whole picture, I am just giving some ideas :-)

That said: Obviously I am not saying we can't provide pre-built packages, but while having this for any GNU/Linux is really easy (I can fire a bunch of Docker containers with all the distributions and versions we need), MacOS is another story.

For MacOS either we get a physical instance to place it somewhere and be able to continuously (I don't know if Geoff has one or how he created the MacOSX instructions), either we get a virtual instance and pay the fees.

So if using Docker or VMs is not an option at all, I will wait for Geoff to answer.

**Comment by StevenBlack** [comment]
@juliogonzalez Thank you for attending to this Julio.  I know it's not easy.  You've given me some good ideas, enough to move forward.  Cheers!

**Comment by GeoffMontee** [comment]
Hi @StevenBlack,

Thanks for using tds_fdw!

Unfortunately, I do not have a Mac, and I don't have any plans to get one any time soon. If someone else would like to provide Mac OS X binaries, I am open to discussing that.

**Comment by TheRevenantStar** [comment]
@StevenBlack can you utilize docker to run the extension in a postresql-server container?
I've included instructions for it in the alpine/docker install instructions( tds_fdw/InstallUbuntu.md )

Otherwise, if you've already solved it, can you close this issue?

**Comment by StevenBlack** [comment]
Thanks @TheRevenantStar.

It’s working for me now; old issue.

Closing.
