### ISSUE TITLE
postgresql 10 support

### ISSUE THREAD

**Issue by gabrimonfa** [tds-fdw/tds_fdw#144]
Hi all,

which is the status of the support for postgresql 10?
I cannot find any information about official support, nor opened issues about problem

**Comment by gabrimonfa** [comment]
I can confirm that current master compiles correctly against postgresql 10 and debian stretch.
A simple read of data in a foreign table works correcty and timing are similar w.r.t version 1.0.7 and postgresql 9.4 (my previous setup).
Obviously an official support would be better.

**Comment by juliogonzalez** [comment]
@gabrimonfa, thank for the report.

As a first step I will add PostgreSQL 10 to the Continous Integration to see if all the tests are able to pass (that way if everyone wants to add new code, we will be able to test it).

If that's the case, I will update the doc and will send a PR for @GeoffMontee

**Comment by juliogonzalez** [comment]
PostgreSQL 10 is now added to the [CI](https://jenkins.juliogonzalez.es/job/tds_fdw-build/).

You can see that tests are running fine (code [here](https://github.com/tds-fdw/tds_fdw/tree/master/tests/tests/postgresql)).

I will not update tds_fdw doc, since only 9.2+ is mention as supported versions, but not sure if @GeoffMontee wants to add anything.

@gabrimonfa feel free to close the issue if you are satisfied, or otherwise wait for Geoff to take a further look.

**Comment by TheRevenantStar** [comment]
@GeoffMontee can you close this one? I think it's dead

**Comment by GeoffMontee** [comment]
Sure. Thanks, @TheRevenantStar.
