### ISSUE TITLE
Dynamic queries?

### ISSUE THREAD

**Issue by nicklaich** [tds-fdw/tds_fdw#201]
Instead of editing pg_foreign_table every time you need to change a query,
something like this could be nice:

CREATE FOREIGN TABLE mssql_customers(
	name varchar,
	age int)
	SERVER mssql_svr
	OPTIONS (query_dynamic, row_estimate_method 'showplan_all');
SET tds_fdw.query_text='select name, age from sales.coustomers where age>10';
SELECT * from mssql_customers;

**Comment by TheRevenantStar** [comment]
What exactly do you need to change in this query to make it dynamic?
Generally speaking, you don’t need to change the query text, just the WHERE
clause in the query “above”.


From: nicklaich <notifications@github.com> <notifications@github.com>
Reply: tds-fdw/tds_fdw
<reply@reply.github.com>
<reply@reply.github.com>
Date: May 23, 2019 at 6:05:22 AM
To: tds-fdw/tds_fdw <tds_fdw@noreply.github.com>
<tds_fdw@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  [tds-fdw/tds_fdw] Dynamic queries? (#201)

Instead of editing pg_foreign_table every time you need to change a query,
something like this could be nice:

CREATE FOREIGN TABLE mssql_customers(
name varchar,
age int)
SERVER mssql_svr
OPTIONS (query_dynamic, row_estimate_method 'showplan_all');
SET tds_fdw.query_text='select name, age from sales.coustomers where
age>10';
SELECT * from mssql_customers;

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tds-fdw/tds_fdw/issues/201?email_source=notifications&email_token=AJXFDFPFT3QWDJYS6F6FQKDPWZ27FA5CNFSM4HO62R7KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GVNWG5A>,
or mute the thread

**Comment by nicklaich** [comment]
Hi!
Generally speaking, i do, because queries can be rather complex, and include joins and withs.
Though, i do agree with result structure is being constant.

**Comment by TheRevenantStar** [comment]
Apologies if I was unclear...
What needs to be dynamic exactly? You provided an example with query text but did not indicate how it would change.

**Comment by nicklaich** [comment]
Well, the query could transform into this, for example:
'select name, max(quantity) from sales.vip_customers c
join sales.orders o where c.id=o.customer
where left(o.item_serial,7)=''es1-521'' group by name'
----
in common, any query that returns the same table structure.
---
Thing is, ATM, queries is the only option to pass filtering and query data to mssql.
And i not sure how modifying system tables could work in multi-user environment.
----
Well, by your questions i guess the topic is not the thing you expect from tds_fdw. Maybe i should poke around dblink_tds instead.
Sorry for taking your time.

**Comment by TheRevenantStar** [comment]
It looks like there is a disconnect between what a query is versus a table.
TDS_FDW is supposed to provide data from another server's table (or view).
The query option is so you can use a query as your data source, instead of having to create a view, not to modify each time you need different data.

It also looks like you are looking for query pushdown (eg. sending the WHERE filters to the foreign server) which is currently an alpha feature.
