### ISSUE TITLE
Support for Centos 8

### ISSUE THREAD

**Issue by MarcelGeo** [tds-fdw/tds_fdw#239]
In documentation, I see installation with yum packages. Is there possibility to install also dnf packages for Centos 8?

**Comment by GeoffMontee** [comment]
Hi @MarcelGeo, 

@devrimgunduz builds tds_fdw RPMs for RHEL/CentOS 8, and he uploads them to the main PostgreSQL repository. For example, in the PostgreSQL 12 repository, you can see a package named `tds_fdw12`:

https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-8Server-x86_64/

Therefore, if you have the official PostgreSQL 12 repository for RHEL/CentOS 8 setup, then you could install tds_fdw by executing the following:

```
sudo yum install tds_fdw12
```

It should also be fine to use `dnf` instead of `yum`.

**Comment by MarcelGeo** [comment]
Thanks, this helps.
