### ISSUE TITLE
Installing from master uses incorrect postgresql libraries

### ISSUE THREAD

**Issue by Smtgr14** [tds-fdw/tds_fdw#78]
If I download a fresh copy of the repo and follow the install instructions,
I get this error in psql after querying a foreign table:
`ERROR:  incompatible library "/usr/lib/postgresql/9.5/lib/tds_fdw.so": version mismatch`
`DETAIL:  Server is version 9.5, library is version 9.4.`

**Comment by Smtgr14** [comment]
Almost forgot, I'm using commit 6404b95

**Comment by GeoffMontee** [comment]
It looks like you are building tds_fdw against PostgreSQL 9.4, but you are installing it on PostgreSQL 9.5. This is probably because I had not completely updated the installation instructions to use PostgreSQL 9.5 throughout. I just updated the install docs now: https://github.com/tds-fdw/tds_fdw/commit/41d2d5212bba59a8a661096567d4726c5b3efc76

**Comment by Smtgr14** [comment]
Do'h should've mentioned I skipped the Installing PostgreSQL section.
That's the trick. I only have postgresql 9.5. I ran the apt-get commands just in case:
`postgresql-9.5 is already the newest version (9.5.2-1).`
`postgresql-client-9.5 is already the newest version (9.5.2-1).`
`postgresql-server-dev-9.5 is already the newest version (9.5.2-1).`

**Comment by Smtgr14** [comment]
I've figured it out. I forgot to actually run git checkout after pulling the latest changes.

**Comment by GeoffMontee** [comment]
Awesome! I'm glad to hear that it's working now.
